# Camera run test
Open camera, s to save, q to quit

In [ ]:
import pyrealsense2 as rs
import numpy as np
import cv2
import os

# Configure RealSense pipeline
pipeline = rs.pipeline()
config = rs.config()

# Enable color and depth streams
config.enable_stream(rs.stream.color, 640, 480, rs.format.bgr8, 30)
config.enable_stream(rs.stream.depth, 640, 480, rs.format.z16, 30)

# Start streaming
pipeline.start(config)

# Create colorizer for depth map
colorizer = rs.colorizer()

# Create folder to save images
SAVE_DIR = "../io/images"
os.makedirs(SAVE_DIR, exist_ok=True)
frame_count = 0

try:
    while True:
        # Wait for a coherent pair of frames: depth and color
        frames = pipeline.wait_for_frames()
        color_frame = frames.get_color_frame()
        depth_frame = frames.get_depth_frame()
        if not color_frame or not depth_frame:
            continue

        # Convert images to numpy arrays
        color_image = np.asanyarray(color_frame.get_data())
        depth_image = np.asanyarray(colorizer.colorize(depth_frame).get_data())
        
        # Print out depth values
        
        depth_map = np.asanyarray(depth_frame.get_data())  
        print(depth_map.dtype)
        print(depth_map.min(), depth_map.max())

        print(f"Depth map values: {depth_map}")
        print(f"Depth image values: {depth_image}")

        # Stack images side by side
        images = np.hstack((color_image, depth_image))

        # Show images
        cv2.imshow('RealSense RGB + Depth', images)

        key = cv2.waitKey(1) & 0xFF # Get key every 1ms
        # Press 'q' to exit
        if key == ord('q'):
            break
        # Press 's' to save images
        elif key == ord('s'):
            color_path = os.path.join(SAVE_DIR, f"color_{frame_count:04d}.png")
            depth_path = os.path.join(SAVE_DIR, f"depth_{frame_count:04d}.png")
            cv2.imwrite(color_path, color_image)
            cv2.imwrite(depth_path, depth_image)
            print(f"[INFO] Saved color to {color_path} and depth to {depth_path}")
            frame_count += 1
finally:
    # Stop streaming
    pipeline.stop()
    cv2.destroyAllWindows()


uint16
0 4297
Depth map values: [[   0    0    0 ...    0    0    0]
 [   0    0    0 ... 2589    0    0]
 [   0    0    0 ... 2578 2589    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]
Depth image values: [[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [244   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [246   0   0]
  [244   0   0]
  [  0   0   0]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]
uint16
0 4297
Depth map values: [[   0    0    0 ...    0    0    0]
 [   0    0    0 ... 

# Print out camera intrinsics

In [2]:
import pyrealsense2 as rs

# Create pipeline
pipeline = rs.pipeline()
config = rs.config()
config.enable_stream(rs.stream.depth, 640, 480, rs.format.z16, 30)
config.enable_stream(rs.stream.color, 640, 480, rs.format.bgr8, 30)

# Start streaming
profile = pipeline.start(config)

# Get stream profile and camera intrinsics
depth_profile = profile.get_stream(rs.stream.depth)
intrinsics = depth_profile.as_video_stream_profile().get_intrinsics()

print("Width:", intrinsics.width)
print("Height:", intrinsics.height)
print("fx:", intrinsics.fx)
print("fy:", intrinsics.fy)
print("ppx (cx):", intrinsics.ppx)
print("ppy (cy):", intrinsics.ppy)
print("Distortion Model:", intrinsics.model)
print("Distortion Coefficients:", intrinsics.coeffs)

# Stop streaming
pipeline.stop()


Width: 640
Height: 480
fx: 386.8893737792969
fy: 386.8893737792969
ppx (cx): 321.6220703125
ppy (cy): 240.8651123046875
Distortion Model: distortion.brown_conrady
Distortion Coefficients: [0.0, 0.0, 0.0, 0.0, 0.0]
